<?php

namespace ContainerHKS42nV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginRedirectListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\LoginRedirectListener' shared autowired service.
     *
     * @return \App\EventListener\LoginRedirectListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'LoginRedirectListener.php';

        return $container->privates['App\\EventListener\\LoginRedirectListener'] = new \App\EventListener\LoginRedirectListener(($container->services['router'] ?? self::getRouterService($container)));
    }
}
