parameters:
    upload_directory: '%kernel.project_dir%/public/uploads'
    
    twilio.sid:        '%env(string:TWILIO_SID)%'
    twilio.auth_token: '%env(string:TWILIO_AUTH_TOKEN)%'
    twilio.from:       '%env(string:TWILIO_FROM)%'
    twilio.admin_phone: '%env(string:ADMIN_PHONE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    

    App\EventListener\LoginRedirectListener:
        tags:
            - { name: kernel.event_subscriber }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
