<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHKS42nV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHKS42nV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHKS42nV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHKS42nV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHKS42nV\App_KernelDevDebugContainer([
    'container.build_hash' => 'HKS42nV',
    'container.build_id' => 'b1b015c6',
    'container.build_time' => 1746718871,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHKS42nV');
